### ISSUE TITLE
error at Editor.Profile

### ISSUE THREAD

**Issue by rudinum** [editor-framework/regl-playground#1]
Hello,
I am trying to play with regl-playground.
After setting up the editor-framework and starting regl-playground I got the error:
Editor.Profile.setDefault is no function.

Can you please help?

**Comment by jwu** [comment]
Hello rudinum,

Sorry for my late reply, I just see this issue right now.

The version of editor-framework used in regl-playground is not public yet. I am slowly developing a public project to replace the editor-framework, but before that happen, I don't think the regl-playground can be run normally.
